# Generated by Django 6.0.7 on 2026-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('v0', 'V0'), ('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3'), ('v4', 'V4'), ('v5', 'V5')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('coming_soon', 'Coming Soon'), ('complete', 'Complete')], default='coming_soon', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
