# Generated by Django 6.0.7 on 2026-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presale_start', models.DateTimeField(blank=True, null=True)),
                ('current_phase', models.CharField(choices=[('v0', 'V0'), ('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3'), ('v4', 'V4'), ('v5', 'V5')], default='v0', max_length=10)),
                ('presale_open', models.BooleanField(default=False)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
