# Generated by Django 5.2.17 on 2026-08-09 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=44)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='joined_phase',
            field=models.CharField(choices=[('v0', 'V0'), ('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3'), ('v4', 'V4'), ('v5', 'V5')], default='v0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='milestone_100_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='milestone_500_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(db_index=True, default='', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(db_index=True, default='', max_length=44, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_at_referral', models.CharField(choices=[('v0', 'V0'), ('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3'), ('v4', 'V4'), ('v5', 'V5')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_via', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
