# Generated by Django 5.2.16 on 2026-08-05 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresaleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasury_address', models.CharField(blank=True, help_text='Base58 Solana address that receives contributions. This is the single canonical address shown on the site.', max_length=44)),
                ('cluster', models.CharField(choices=[('mainnet-beta', 'Mainnet Beta'), ('devnet', 'Devnet')], default='mainnet-beta', max_length=20)),
                ('rpc_url', models.URLField(blank=True, help_text='Solana RPC endpoint used by the indexer. Leave blank to use the public endpoint for the selected cluster (rate limited).')),
                ('soft_cap_lamports', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hard_cap_lamports', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_contribution_lamports', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_contribution_lamports', models.BigIntegerField(default=0, help_text='Per-address cap across all their contributions. 0 means no cap.', validators=[django.core.validators.MinValueValidator(0)])),
                ('token_price_lamports', models.BigIntegerField(default=0, help_text='Price of one token, in lamports. 0 disables allocation math.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paused', models.BooleanField(default=False, help_text='Hides the contribution address on the site without touching timing.')),
                ('last_indexed_signature', models.CharField(blank=True, max_length=88)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Presale configuration',
                'verbose_name_plural': 'Presale configuration',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_lamports', models.BigIntegerField(help_text='Minimum cumulative contribution to qualify for this tier.', validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_bps', models.PositiveIntegerField(default=0, help_text='Bonus in basis points (100 bps = 1%%) applied to the token allocation.')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'min_lamports'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=88, unique=True)),
                ('sender_address', models.CharField(db_index=True, max_length=44)),
                ('lamports', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('slot', models.BigIntegerField()),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('refunded', 'Refunded'), ('excluded', 'Excluded')], default='confirmed', max_length=20)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-slot'],
                'indexes': [models.Index(fields=['status', '-slot'], name='presale_con_status_011722_idx')],
            },
        ),
    ]
