# Generated by Django 5.2.16 on 2026-08-05 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presaleconfig',
            name='launch_price_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Advertised launch price per token in USD, e.g. 0.010.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='presaleconfig',
            name='presale_price_usd',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Advertised presale price per token in USD, e.g. 0.008.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='presaleconfig',
            name='sol_usd_rate_at_pricing',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The SOL/USD rate token_price_lamports was derived from. Recorded so the advertised USD price can be audited against the rate used.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='presaleconfig',
            name='token_price_lamports',
            field=models.BigIntegerField(default=0, help_text='Price of one token, in lamports. This is the number that decides allocations. 0 disables allocation math.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
