# Generated by Django 5.2.16 on 2026-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presale', '0002_presaleconfig_launch_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='base_tokens',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Tokens earned by this contribution alone, before any tier bonus. Null when the presale had no token price configured at credit time.', max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='token_price_lamports_at_credit',
            field=models.BigIntegerField(default=0, help_text='The lamports-per-token price used for this contribution. Kept so the allocation can be re-derived and audited after a re-price.'),
        ),
        migrations.AddField(
            model_name='presaleconfig',
            name='sol_usd_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='presaleconfig',
            name='sol_usd_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
